### ISSUE TITLE
Fix interactive toggling of todo checkboxes

### ISSUE THREAD

**Issue by markmhx** [blockstack/todos#56]
Todos don't toggle state visually when checked or unchecked, although the data state change is working via Gaia as reflected by accurate visual state upon page load.

![image](https://user-images.githubusercontent.com/28991/100648401-2ca78900-3341-11eb-9025-2f6a48ba6aaf.png)

**Comment by sherwyn11** [comment]
Created a pull request for the same #59

**Comment by sherwyn11** [comment]
Created a pull request to fix the freezing issue of the checkbox #61

**Comment by sherwyn11** [comment]
Since the bug is fixed #61, this issue can now be closed?

**Comment by markmhx** [comment]
Yep! Thanks again for the help here.
