### ISSUE TITLE
Add share options for todo lists

### ISSUE THREAD

**Issue by vsund** [blockstack/todos#8]
To better share what you did or plan to do, it would be handy to be able to share lists. The integration of this app into the [daily scrum](https://github.com/blockstack/daily-scrum/issues) would mainly benefit from this with i.e. a "Post this link to GitHub" feature.

**Comment by jackzampolin** [comment]
One good one would be to export it to a `*.md` file. This would make it much easier to post into github. I found this [`json2md`](https://github.com/IonicaBizau/json2md) lib for JS that could help...
